# Preset: Default
# Vyvážené kvóty pro obecné použití

name: default
description: Výchozí preset – vyvážené rozložení jazyků a nálad.

target_duration: 14400  # 4 hodiny

quotas:
  "4":   # Jazyk
    "639": 50   # Čeština
    "667": 35   # Angličtina
    "644": 15   # Slovenština
  #"6":   # Nálada
  #  "45": 40   # Klidná
  #  "46": 40   # Chvály
  #  "47": 20   # Instrumentální

soft_filter:
  chars:
    "2": #Žánr
      exclude: [292,472]
    "28": # časové
      include: [652]
  duration:
    min: 60
    max: 600
  year:
    min: 1970

tolerance: 120
