# Preset: Default
# Vyvážené kvóty pro obecné použití

name: default
description: Výchozí preset – vyvážené rozložení jazyků a nálad.

target_duration: 14400  # 4 hodiny

quotas:
  "4":   # Jazyk
    "639": 45   # Čeština
    "667": 30   # Angličtina
    "644": 15   # Slovenština
    # ostatní 10 %
  
  #"6":   # Nálada
  #  "45": 40   # Klidná
  #  "46": 40   # Chvály
  #  "47": 20   # Instrumentální

  "28": # časové
    "652": 5 # Velikonoční 

soft_filter:
  chars:
    "2": #Žánr
      exclude: # nevybere tyto charakteristiky
        - 292 # kom. - barok
        - 472 # metal
        - 148 # gregoriánský chorál
    "5":
      exclude:
        - 656 # Dětská


    "28": # časové
      include: ~ # vyřadí všechny časové
      #  - 652 # Velikonoční
  duration: # sekundy
    min: 60
    max: 359
  year:
    min: 1970

tolerance: 120
