name: ODP
description: Odpolední nálada
target_duration: 14400
quotas:
  '28':
    '652': 5
  '2':
    '10': 0
    '11': 0
    '12': 0
  '4':
    '66': 23
    '639': 45
    '644': 15
soft_filter:
  duration:
    min: 60
    max: 359
  year:
    min: 2010
  chars:
    '28':
      include: null
tolerance: 120
exclude_tracks: []
exclude_artists: []
exclude_albums: []
